# Generated by Django 2.1.8 on 2019-09-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='introducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
                ('division', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=150)),
            ],
        ),
    ]
